name: flutter_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you plan to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  awesome_dialog: ^3.3.0
  http: ^1.6.0
  drop_down_list: ^2.1.1
  shared_preferences: ^2.5.4
  geolocator: ^14.0.2


dev_dependencies:
  flutter_launcher_icons: "^0.14.4"
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

 
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/flutter_logo_1.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: VariableFont
      fonts:
        - asset: fonts/Italic-VariableFont.ttf
    - family: Playwrite
      fonts:
        - asset: fonts/PlaywriteGBJGuides-Regular.ttf
        - asset: fonts/PlaywriteGBJGuides-Italic.ttf
          style: italic